using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiggerPixelArt
{
    public enum BlockKind : byte
    {
        Default = 0,
        Half = 1,
        Fence = 2,
        DiagonalWest = 3,
        DiagonalEast = 4,
        DiagonalSouth = 5,
        DiagonalNorth = 6,
        StairNorth = 7,
        StairSouth = 8,
        StairWest = 9,
        StairEast = 10,
        HalfWallNorth = 11,
        HalfWallSouth = 12,
        HalfWallEast = 13,
        HalfWallWest = 14,
        Quarter = 0x10,
        QuarterOnWallEast = 17,
        QuarterOnWallNorth = 18,
        QuarterOnWallSouth = 19,
        QuarterOnWallWest = 20,
        FenceOnWallSouthNorth = 21,
        FenceOnWallEastWest = 22,
        Third = 25,
        ThirdOnWallEast = 26,
        ThirdOnWallWest = 27,
        ThirdOnWallSouth = 28,
        ThirdOnWallNorth = 29,
        DiagonalOnWallWestRight = 30,
        DiagonalOnWallWestLeft = 0x1F,
        DiagonalOnWallWestTop = 0x20,
        DiagonalOnWallWestBottom = 33,
        DiagonalOnWallEastRight = 34,
        DiagonalOnWallEastLeft = 35,
        DiagonalOnWallEastTop = 36,
        DiagonalOnWallEastBottom = 37,
        DiagonalOnWallSouthRight = 38,
        DiagonalOnWallSouthLeft = 39,
        DiagonalOnWallSouthTop = 40,
        DiagonalOnWallSouthBottom = 41,
        DiagonalOnWallNorthRight = 42,
        DiagonalOnWallNorthLeft = 43,
        DiagonalOnWallNorthTop = 44,
        DiagonalOnWallNorthBottom = 45,
        StairOnWallNorthRight = 46,
        StairOnWallNorthLeft = 47,
        StairOnWallNorthTop = 48,
        StairOnWallNorthBottom = 49,
        StairOnWallSouthRight = 50,
        StairOnWallSouthLeft = 51,
        StairOnWallSouthTop = 52,
        StairOnWallSouthBottom = 53,
        StairOnWallWestRight = 54,
        StairOnWallWestLeft = 55,
        StairOnWallWestTop = 56,
        StairOnWallWestBottom = 57,
        StairOnWallEastRight = 58,
        StairOnWallEastLeft = 59,
        StairOnWallEastTop = 60,
        StairOnWallEastBottom = 61,
        CornerEast = 62,
        CornerWest = 0x3F,
        CornerNorth = 0x40,
        CornerSouth = 65,
        FenceWest = 66,
        FenceEast = 67,
        FenceNorth = 68,
        FenceSouth = 69,
        EastFenceWest = 70,
        EastFenceEast = 71,
        EastFenceNorth = 72,
        EastFenceSouth = 73,
        WestFenceWest = 74,
        WestFenceEast = 75,
        WestFenceNorth = 76,
        WestFenceSouth = 77,
        NorthFenceWest = 78,
        NorthFenceEast = 79,
        NorthFenceNorth = 80,
        NorthFenceSouth = 81,
        SouthFenceWest = 82,
        SouthFenceEast = 83,
        SouthFenceNorth = 84,
        SouthFenceSouth = 85,
        CornerStairEast = 86,
        CornerStairWest = 87,
        CornerStairSouth = 88,
        CornerStairNorth = 89,
        Flip = 0x80,
        HalfFlip = 129,
        DiagonalWestFlip = 131,
        DiagonalEastFlip = 132,
        DiagonalSouthFlip = 133,
        DiagonalNorthFlip = 134,
        StairNorthFlip = 135,
        StairSouthFlip = 136,
        StairWestFlip = 137,
        StairEastFlip = 138,
        QuarterFlip = 144,
        ThirdFlip = 153,
        DiagonalEastFlip2 = 161,
        DiagonalWestFlip2 = 165,
        DiagonalNorthFlip2 = 173,
    }
}
